# vim: set ft=ansible:
---
- name: Register host(s)
  hosts: "{{ hosts_to_register }}"
  vars:
    rhn_username: "{{ lookup('env', 'RHN_USERNAME') | default(omit, true) }}"
    rhn_password: "{{ lookup('env', 'RHN_PASSWORD') | default(omit, true) }}"
  tasks:
  - name: Enable subscription-manager
    ini_file:
      dest: /etc/yum/pluginconf.d/subscription-manager.conf
      section: main
      option: enabled
      value: 1

  - name: Register host
    redhat_subscription:
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
      state: present
      pool: "^OpenShift Enterprise High Touch Beta$"

  - name: Enable rhui extras and optional channels
    command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional

  - name: Disable all known rhsm repos
    command: subscription-manager repos --disable='*'

  - name: Subscribe only to the ose beta repo
    command: >
      subscription-manager repos --enable="rhel-server-7-ose-beta-rpms"

  - name: Update current package set
    yum:
      name: '*'
      state: latest

